{
 "title": "Power Dashboard",
 "description": "Power Related Dashboard using prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "System Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CUDA Version",
   "type": "stat",
   "description": "CUDA Version",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_nvgpu_sysinfo", "legendFormat": "{{cuda_v}}" }
   ]
  },
  {
   "title": "CUDA Version",
   "type": "stat",
   "description": "CUDA Version",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_nvgpu_sysinfo", "legendFormat": "{{cuda_v}}" }
   ]
  },
  {
   "title": "NVIDIA Driver Version",
   "type": "stat",
   "description": "NVIDIA Driver Version",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_nvgpu_sysinfo", "legendFormat": "{{driver_v}}" }
   ]
  },
  { "title": "GPU Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "NVIDIA GPU Temperature",
   "type": "timeseries",
   "description": "The time-series for temperature of NVIDIA GPU",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_nvgpu_temp",
     "legendFormat": "Node(Instance-Job): {{instance}}-{{job}} / GPU: {{index}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "gauge",
   "description": "GPU Utilization",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_nvgpu_util", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "NVIDIA GPU Clock",
   "type": "timeseries",
   "description": "The time-series for clock of NVIDIA GPU",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "node_nvgpu_clk",
     "legendFormat": "Node(Instance-Job): {{instance}}-{{job}} / GPU: {{index}} / Type: {{type}}"
    }
   ]
  },
  {
   "title": "GPU Bus Type",
   "type": "stat",
   "description": "GPU Bus Type",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_nvgpu_gpuinfo", "legendFormat": "{{bus_type}}" }
   ]
  },
  {
   "title": "GPU Compute Mode",
   "type": "stat",
   "description": "GPU Compute Mode",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_nvgpu_compute_mode", "legendFormat": "{{mode}}" }
   ]
  },
  {
   "title": "GPU Persistence Mode",
   "type": "stat",
   "description": "GPU Persistence Mode",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_nvgpu_persis_mode", "legendFormat": "{{mode}}" }
   ]
  },
  {
   "title": "GPU Fan Speed Limit",
   "type": "stat",
   "description": "GPU Min/Max Fan Speed",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_nvgpu_min_fan_speed", "legendFormat": "__auto" },
    { "expr": "node_nvgpu_max_fan_speed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU UUID",
   "type": "stat",
   "description": "GPU UUID",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_nvgpu_gpuinfo", "legendFormat": "{{uuid}}" }
   ]
  },
  {
   "title": "GPU Name",
   "type": "stat",
   "description": "GPU Name",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_nvgpu_gpuinfo", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "NVIDIA GPU Power",
   "type": "timeseries",
   "description": "The time-series for Power Usage of NVIDIA GPU",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "targets": [
    {
     "expr": "node_nvgpu_power_usage",
     "legendFormat": "Node(Instance-Job): {{instance}}-{{job}} / GPU: {{index}}"
    },
    {
     "expr": "node_nvgpu_power_enforce_limit",
     "legendFormat": "Node(Instance-Job): {{instance}}-{{job}} / GPU: {{index}}"
    }
   ]
  },
  {
   "title": "NVIDIA GPU Memory Usage",
   "type": "timeseries",
   "description": "The time-series for Memory Usage of NVIDIA GPU",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_nvgpu_mem_total",
     "legendFormat": "Node(Instance-Job): {{instance}}-{{job}} / GPU: {{index}} / MemTotal"
    },
    {
     "expr": "node_nvgpu_mem_used",
     "legendFormat": "Node(Instance-Job): {{instance}}-{{job}} / GPU: {{index}} / MemUsed"
    },
    {
     "expr": "node_nvgpu_mem_free",
     "legendFormat": "Node(Instance-Job): {{instance}}-{{job}} / GPU: {{index}} / MemFree"
    }
   ]
  },
  {
   "title": "NVIDIA GPU App Clock",
   "type": "timeseries",
   "description": "The time-series for applications clock of NVIDIA GPU",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "node_nvgpu_appclk",
     "legendFormat": "Node(Instance-Job): {{instance}}-{{job}} / GPU: {{index}}"
    }
   ]
  },
  {
   "title": "NVIDIA GPU Fanspeed",
   "type": "timeseries",
   "description": "The time-series for Fan Speed of NVIDIA GPU",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "node_nvgpu_fan_speed",
     "legendFormat": "Node(Instance-Job): {{instance}}-{{job}} / GPU: {{index}} / Fan: {{fan}}"
    }
   ]
  }
 ]
}